### ISSUE TITLE
Error - attempt to call 'get_metadata' (a nil value)

### ISSUE THREAD

**Issue by ecosse3** [tzachar/compe-tabnine#11]
Hi, yesterday after compe-tabnine update via vim-plug I have an error when pressing in insert mode. Compe stopped working at all.

![image](https://user-images.githubusercontent.com/17691791/113152824-ce2ee080-9236-11eb-8fe2-0e93dd2d1b6f.png)

Space is mapped to `compe#complete()`

NVIM v0.5.0-dev+nightly-166-gc20ae3aad
Build type: Release
LuaJIT 2.1.0-beta3
macOs Catalina 10.15.7

My full config: https://github.com/ecosse3/nvim

Didn't try to reproduce yet on minimal config.

The same problem mentioned here: https://github.com/hrsh7th/nvim-compe/issues/306

***When I commented out tabnine plugin from nvim-compe sources then it works correctly.***

**Comment by tzachar** [comment]
This should be solved with the latest commit: ae8001c
