### ISSUE TITLE
Error with tabnine

### ISSUE THREAD

**Issue by JoseConseco** [tzachar/compe-tabnine#15]
![image](https://user-images.githubusercontent.com/13521338/115115378-862cef00-9f94-11eb-9112-8e567d6531bb.png)
I think it may be caused by setting:
![image](https://user-images.githubusercontent.com/13521338/115115415-a78ddb00-9f94-11eb-99ae-222b266c2dcc.png)
I just want auto completion to show right after I press dot - to show eg. available class methods, without having to enter one or two character for popup to show.

**Comment by tzachar** [comment]
Having min_length set to 1 work for me with '.'
Anyway, this should be fixed in 8fe21b5

**Comment by JoseConseco** [comment]
thanks it work now.  I did not change compe settings except min_length, that is why I thought it was causing the mess...
