### ISSUE TITLE
Typo `diabled` in source may lead to bug?

### ISSUE THREAD

**Issue by LinuCC** [tzachar/compe-tabnine#18]
Just noticed a typo that left me wondering whether it impacted the functionality.
See in `init.lua`:

```lua
local function is_enabled()
	local conf = compe_config.get()
	local diabled = get_paths(conf, {'source', 'tabnine', 'disabled'})
	return not disabled
end
```
I highly suspect its meant to be `disabled` instead of `diabled`?

**Comment by tzachar** [comment]
10x.

fixed in cb7f225
