### ISSUE TITLE
Error installing on linux

### ISSUE THREAD

**Issue by ofrades** [tzachar/compe-tabnine#2]
E5108: Error executing lua Vim:E475: Invalid value for argument cmd: '/home/ofrades/.local/share/nvim/site/pack/packer/start/compe-tabnine/binaries/TabNine_Linux

**Comment by tzachar** [comment]
Does the file exist in the required path? 
What is the output of 
```sh
ls -al /home/ofrades/.local/share/nvim/site/pack/packer/start/compe-tabnine/binaries/TabNine_Linux
```

**Comment by ofrades** [comment]
No, binaries was not created. What I did was to run `sh /home/ofrades/.local/share/nvim/site/pack/packer/start/compe-tabnine/install.sh` manually. So probably the problem was my `      use {"tzachar/compe-tabnine", run = "./install.sh"}
`

**Comment by tzachar** [comment]
Which plugin manager are you using?

**Comment by ofrades** [comment]
I am using [Packer](https://github.com/wbthomason/packer.nvim)

**Comment by tzachar** [comment]
Can you try deleting the plugin, and running Packer install again, attaching the output of the install process?
I don't use Packet personally, so a minimal .vimrc using it would be helpful to solve the issue

**Comment by klooj** [comment]
i use packer. try changing into ... /pack/packer/start/compe-tabnine/  and then manually run ./install.sh instead of running it through packer or from a different directory.

**Comment by tzachar** [comment]
This looks like an issue with Packer.
It looks like the install script is not executed.

**Comment by tzachar** [comment]
closing,
if someone has a solution, please post it.

**Comment by evolify** [comment]
The same issue with packer in macOS

**Comment by tzachar** [comment]
Well, I have no experience with packer.
Feel free to submit a patch :)
