### ISSUE TITLE
Other sources are not shown when tabnine is enabled and requesting completion for 0 length

### ISSUE THREAD

**Issue by Gelio** [tzachar/compe-tabnine#20]
Hey! Thanks for the great plugin

I have been using it for some time and I have noticed something that is not ideal in my view. When requesting completion when I did not type any input yet (to get the list of possible values from LSP, meaning I did not type any letters for the word yet), I am only getting TN completions, and the completions from LSP are not shown.

![image](https://user-images.githubusercontent.com/889383/115896519-cd672400-a45b-11eb-9d07-614b345dfe70.png)

It works fine after I type a letter:
![image](https://user-images.githubusercontent.com/889383/115896566-d8ba4f80-a45b-11eb-90bf-fd7f932150e4.png)

I have tried changing the priority of the `tabnine` source to be lower than `lsp`:
```lua
  source = {
    path = true;
    buffer = true;
    calc = true;
    nvim_lsp = { priority = 1000 };
    nvim_lua = true;
    vsnip = false;
    tabnine = { priority = 999 };
  };
```

but that does not help. I have also tried changing `compe`'s `min_length` to 0:
```lua
  min_length = 0;
```

That did not help either.

The only thing that helps get completions when I haven't typed any letter yet is disabling the `tabnine` source
```lua
    tabnine = false;
```

Then I get LSP completions without changing `min_length` or any priorities.
![image](https://user-images.githubusercontent.com/889383/115897161-6d24b200-a45c-11eb-84e2-6d32a968373a.png)

How do I get tabnine completions for 0-letter inputs to not overwrite the LSP completions?

Relevant parts of my config:
https://github.com/Gelio/ubuntu-dotfiles/blob/72b863b1a1e91336e51f998f1abc95660da91525/configs/neovim.lua#L67-L90
https://github.com/Gelio/ubuntu-dotfiles/blob/72b863b1a1e91336e51f998f1abc95660da91525/configs/neovim.vim#L196-L205

**Comment by tzachar** [comment]
I believe this is a bug with compe. It has nothing to do with compe-tabnine. 
You can see from your example that the only source used when tabnine is disabled is lsp. Why no buffer sugestions? 
You can set LSP to false, and see another source poping up to be the only source of completion.
I suggest you open a bug in compe, and give an example of this behaviour using only the builtin sources.

**Comment by Gelio** [comment]
> You can see from your example that the only source used when tabnine is disabled is lsp. Why no buffer sugestions?

There were so many LSP suggestions that the buffer ones did not make it into the screenshot. They are there, though.

In all screenshots below I am requesting completions not having typed any letters of the word.

With `tabnine` disabled:
![image](https://user-images.githubusercontent.com/889383/115954814-42d20380-a4f3-11eb-9ba7-822175bafa50.png)

With `tabnine` enabled:
![image](https://user-images.githubusercontent.com/889383/115954729-dc4ce580-a4f2-11eb-9761-0c697aebae61.png)

The weird thing is that the suggestions are correct (LSP-ones are on top) when the code is slightly different, and I'm requesting completions for an empty line inside of the `{}` (`tabnine` is enabled in both screenshots):
![image](https://user-images.githubusercontent.com/889383/115954764-0b635700-a4f3-11eb-8e74-66eac0d64eb7.png)
![image](https://user-images.githubusercontent.com/889383/115954769-1322fb80-a4f3-11eb-92a2-ef2f586d4d6b.png)
 
---

Anyway, since you're saying this is likely a bug in compe, I'll open an issue there (EDIT: https://github.com/hrsh7th/nvim-compe/issues/346), thanks for the time 👍
