### ISSUE TITLE
install.sh not executable error

### ISSUE THREAD

**Issue by cronyakatsuki** [tzachar/compe-tabnine#23]
While installing using Packer I had an error that told me that install.sh is not an executable.

I fixed that by instead of using `use {'tzachar/compe-tabnine', run='./install.sh'}` I changed it into `use {'tzachar/compe-tabnine', run='chmod +x install.sh; ./install.sh'}` and the it all worked. You will probably need to update your README.

**Comment by tzachar** [comment]
This is probably a local issue with your git or packer config.
The install script is set to be executable in git:
```sh
git ls-tree HEAD install.sh
100755 blob 6b36b7fb5bf53e55705cafabd81a6aee537fdd12	install.sh
```
The mode is `755`, so the file should be executable.
Try cloning the repo by hand and see if the file is executable.

**Comment by cronyakatsuki** [comment]
it is executable when I clone it with git normally, must be some bug then with packer.
