### ISSUE TITLE
[Help] Windows 10 Pro x64 installation

### ISSUE THREAD

**Issue by pidgeon777** [tzachar/compe-tabnine#26]
Hello, how would I manually install this plugin in a Windows 10 Pro x64 machine?

Especially for the TabNine binary part...

**Comment by tzachar** [comment]
For the binary, you need to patch the install.sh to run on windows.
There are PowerShell versions of this script in other plugins, you can start from there.
As for the plugin itself, it depends on the plugin manager you use.

**Comment by pidgeon777** [comment]
Nevermind, I manually solved this by doing:

1. Check what is the latest *TabNine* binary available:

$VERSION = https://update.tabnine.com/bundles/version

2. Download it:

https://update.tabnine.com/bundles/$VERSION/$TARGET/TabNine.zip

> $TARGET is `x86_64-pc-windows-gnu` in case of Windows 10 x64.

3. Extract the *TabNine* binary archive into the `binary` folder to be placed into the `compe-tabnine` plugin path.

> E.g.: C:\Users\username\AppData\Local\nvim-data\site\pack\packer\opt\compe-tabnine\binaries

4. Rename `TabNine.exe` to `TabNine_Windows.exe`.
