### ISSUE TITLE
enabling 'Take a long shot:' option in TN gives weird suggestions in compe

### ISSUE THREAD

**Issue by JoseConseco** [tzachar/compe-tabnine#27]
After enabling this property (I think its new in TN settings)
![image](https://user-images.githubusercontent.com/13521338/120559791-f3d89180-c401-11eb-89f1-5ab1a8c0c2c6.png)
I get some 'ugly' looking suggestions:
![image](https://user-images.githubusercontent.com/13521338/120560181-97c23d00-c402-11eb-8056-217e3aebd09a.png)
I'm not sure what is going on.

**Comment by tzachar** [comment]
The ^@ signifies a new line.
