### ISSUE TITLE
Could you add a matching items of settings ?

### ISSUE THREAD

**Issue by PHSix** [tzachar/compe-tabnine#3]
I found that in this plugin you set the number of matching items to 20, but when I use tabnine, I don't need so many matching items, because it affects me to select the LSP completions.

**Comment by tzachar** [comment]
Check d717a95
you can now configure it via :
```viml
let g:compe.source.tabnine = {}                                                                                                                                               
let g:compe.source.tabnine.max_line = 1000                                                                                                                                    
let g:compe.source.tabnine.max_num_results = 6              
```

**Comment by PHSix** [comment]
> Check [d717a95](https://github.com/tzachar/compe-tabnine/commit/d717a953dbb745289ea794e86e32deb3750a3a18)
> you can now configure it via :
> 
> ```viml
> let g:compe.source.tabnine = {}                                                                                                                                               
> let g:compe.source.tabnine.max_line = 1000                                                                                                                                    
> let g:compe.source.tabnine.max_num_results = 6              
> ```

ok. Thanks!
