### ISSUE TITLE
Multiline Suggestions Seems to break Compe 

### ISSUE THREAD

**Issue by vsedov** [tzachar/compe-tabnine#30]
Not sure if its just me, but every time Ive enabled Tabnine with multiline  and use it : 
I get the following 
![image](https://user-images.githubusercontent.com/28804392/124333685-df1c2480-db8c-11eb-8c87-ff563f370074.png)

Gives the following error 
![image](https://user-images.githubusercontent.com/28804392/124333698-ea6f5000-db8c-11eb-953c-d155a1a724e2.png)

Then Compe just stops working with this. Not really sure whats going on .

**Comment by tzachar** [comment]
Thanks for the issue.
