### ISSUE TITLE
How to enable tabnine pro ?

### ISSUE THREAD

**Issue by ashishbinu** [tzachar/compe-tabnine#31]
I have installed this plugin to get tabnine completions but I couldn't find any way to enable tabnine pro in the docs.

**Comment by tzachar** [comment]
This is not related to this plugin.
But you can type `TabNine::congif` in any buffer and TabNine will pop up a configuration interface in you browser where you can enter your key.

**Comment by ashishbinu** [comment]
> This is not related to this plugin.
> But you can type `TabNine::congif` in any buffer and TabNine will pop up a configuration interface in you browser where you can enter your key.
> 

Didn't know about it . Thanks for mentioning it.
